//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARControlMaestro
    {
        public int ControlId { get; set; }
        public string Control { get; set; }
        public string Valor { get; set; }
        public bool Sistema { get; set; }
        public bool Activo { get; set; }
        public bool ControlSencillo { get; set; }
        public Nullable<int> ModuloId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
