//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARtblInventarioFisico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARtblInventarioFisico()
        {
            this.ARtblInventarioFisicoDetalle = new HashSet<ARtblInventarioFisicoDetalle>();
        }
    
        public int InventarioFisicoId { get; set; }
        public string Codigo { get; set; }
        public string AlmacenId { get; set; }
        public string Almacen { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> IniciadoPorId { get; set; }
        public Nullable<decimal> MontoAjuste { get; set; }
        public Nullable<int> ResponsableId { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual GRtblUsuario GRtblUsuario1 { get; set; }
        public virtual GRtblUsuario GRtblUsuario2 { get; set; }
        public virtual RHtblEmpleado RHtblEmpleado { get; set; }
        public virtual tblAlmacen tblAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalle { get; set; }
    }
}
