//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARtblInventarioMovimientoAgrupador
    {
        public int InventarioMovtoAgrupadorId { get; set; }
        public string CodigoAgrupador { get; set; }
        public int TipoMovimientoId { get; set; }
        public Nullable<int> ReferenciaMovtoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> PolizaId { get; set; }
    
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual tblPoliza tblPoliza { get; set; }
    }
}
