//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtblInvitacionCompraDetallePrecioProveedor
    {
        public long InvitacionCompraDetallePrecioProveedorId { get; set; }
        public int InvitacionCompraDetalleId { get; set; }
        public int ProveedorId { get; set; }
        public decimal PrecioArticulo { get; set; }
        public Nullable<bool> Ganador { get; set; }
        public string Comentario { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ARtblInvitacionCompraDetalle ARtblInvitacionCompraDetalle { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual tblProveedor tblProveedor { get; set; }
    }
}
