//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARtblInventarioMovimiento
    {
        public long InventarioMovtoId { get; set; }
        public Nullable<int> InventarioMovtoAgrupadorId { get; set; }
        public int AlmacenProductoId { get; set; }
        public int UnidadMedidaId { get; set; }
        public decimal CantidadMovimiento { get; set; }
        public int TipoMovimientoId { get; set; }
        public decimal CantidadAntesMovto { get; set; }
        public int TipoCostoArticuloId { get; set; }
        public string MotivoMovto { get; set; }
        public Nullable<long> ReferenciaMovtoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal CostoPromedio { get; set; }
    
        public virtual ARtblAlmacenProducto ARtblAlmacenProducto { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro1 { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual tblUnidadDeMedida tblUnidadDeMedida { get; set; }
    }
}
