//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARtblInventarioAjusteDetalle
    {
        public int InventarioAjusteDetalleId { get; set; }
        public int InventarioAjusteId { get; set; }
        public string AlmacenId { get; set; }
        public string UnidadAdministrativaId { get; set; }
        public string ProyectoId { get; set; }
        public string FuenteFinanciamientoId { get; set; }
        public string TipoGastoId { get; set; }
        public string ProductoId { get; set; }
        public string Descripcion { get; set; }
        public int CuentaPresupuestalId { get; set; }
        public int UnidadMedidaId { get; set; }
        public decimal CostoUnitario { get; set; }
        public int TipoMovimientoId { get; set; }
        public int ConceptoAjusteId { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ExistenciaActual { get; set; }
        public decimal ExistenciaFinal { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.Guid> ArchivoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ARtblInventarioAjuste ARtblInventarioAjuste { get; set; }
        public virtual GRtblArchivo GRtblArchivo { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual tblAlmacen tblAlmacen { get; set; }
        public virtual tblCuentaPresupuestalEgr tblCuentaPresupuestalEgr { get; set; }
        public virtual tblDependencia tblDependencia { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblRamo tblRamo { get; set; }
        public virtual tblTipoGasto tblTipoGasto { get; set; }
        public virtual tblUnidadDeMedida tblUnidadDeMedida { get; set; }
        public virtual ARtblControlMaestroConceptoAjusteInventario ARtblControlMaestroConceptoAjusteInventario { get; set; }
    }
}
