//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARtblAlmacenProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARtblAlmacenProducto()
        {
            this.ARtblInventarioFisicoDetalles = new HashSet<ARtblInventarioFisicoDetalle>();
            this.ARtblInventarioMovimiento = new HashSet<ARtblInventarioMovimiento>();
            this.ARtblTransferenciaMovto = new HashSet<ARtblTransferenciaMovto>();
            this.ARtblTransferenciaMovto1 = new HashSet<ARtblTransferenciaMovto>();
        }
    
        public int AlmacenProductoId { get; set; }
        public string ProductoId { get; set; }
        public string AlmacenId { get; set; }
        public int CuentaPresupuestalId { get; set; }
        public decimal Cantidad { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalles { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual GRtblUsuario GRtblUsuario1 { get; set; }
        public virtual tblAlmacen tblAlmacen { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblCuentaPresupuestalEgr tblCuentaPresupuestalEgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimiento> ARtblInventarioMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferenciaMovto> ARtblTransferenciaMovto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferenciaMovto> ARtblTransferenciaMovto1 { get; set; }
    }
}
