//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARvwListadoInventarioFisico
    {
        public int InventarioFisicoId { get; set; }
        public string Codigo { get; set; }
        public string Fecha { get; set; }
        public string Almacen { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> MontoAjuste { get; set; }
        public string Estatus { get; set; }
    }
}
