//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARvwListadoConfiguracionArea
    {
        public int ConfiguracionAreaId { get; set; }
        public string AreaId { get; set; }
        public string Comentarios { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public string Codigo { get; set; }
        public string Area { get; set; }
        public int Proyectos { get; set; }
        public int UnidadesAdministrativas { get; set; }
        public int Almacenes { get; set; }
        public int EstatusId { get; set; }
    }
}
