//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARvwListadoOrdenCompra
    {
        public int OrdenCompraId { get; set; }
        public string FechaOC { get; set; }
        public string Proveedor { get; set; }
        public double MontoOC { get; set; }
        public string Status { get; set; }
        public string Estatus { get; set; }
        public Nullable<bool> PermiteEditar { get; set; }
        public Nullable<bool> PermiteCancelar { get; set; }
    }
}
