//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARvwListadoInvitacionCompra
    {
        public int InvitacionCompraId { get; set; }
        public string CodigoInvitacion { get; set; }
        public string Fecha { get; set; }
        public string AlmacenId { get; set; }
        public string Almacen { get; set; }
        public int Proveedores { get; set; }
        public int Cotizaciones { get; set; }
        public decimal MontoInvitacion { get; set; }
        public int EstatusId { get; set; }
        public string Estatus { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> PermiteEditar { get; set; }
        public Nullable<bool> PermiteCancelar { get; set; }
    }
}
