//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARvwListadoOrdenCompraRecibo
    {
        public int CompraId { get; set; }
        public string FechaRecibo { get; set; }
        public int CodigoOC { get; set; }
        public string FechaOC { get; set; }
        public string Proveedor { get; set; }
        public string Estatus { get; set; }
    }
}
