//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAACGContext : DbContext
    {
        public SAACGContext()
            : base("name=SAACGContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARtblControlMaestroConfiguracionArea> ARtblControlMaestroConfiguracionArea { get; set; }
        public virtual DbSet<ARtblControlMaestroConfiguracionAreaAlmacen> ARtblControlMaestroConfiguracionAreaAlmacen { get; set; }
        public virtual DbSet<ARtblControlMaestroConfiguracionAreaProyecto> ARtblControlMaestroConfiguracionAreaProyecto { get; set; }
        public virtual DbSet<ARtblControlMaestroConfiguracionMontoCompra> ARtblControlMaestroConfiguracionMontoCompra { get; set; }
        public virtual DbSet<ARtblInventarioAjuste> ARtblInventarioAjuste { get; set; }
        public virtual DbSet<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalle { get; set; }
        public virtual DbSet<ARtblProveedorProspecto> ARtblProveedorProspecto { get; set; }
        public virtual DbSet<ARtblRequisicionMaterial> ARtblRequisicionMaterial { get; set; }
        public virtual DbSet<ARtblRequisicionMaterialDetalle> ARtblRequisicionMaterialDetalle { get; set; }
        public virtual DbSet<ARtblAlmacenProducto> ARtblAlmacenProducto { get; set; }
        public virtual DbSet<GRtblControlMaestro> GRtblControlMaestro { get; set; }
        public virtual DbSet<GRtblUsuario> GRtblUsuario { get; set; }
        public virtual DbSet<tblCatalogoCuenta> tblCatalogoCuenta { get; set; }
        public virtual DbSet<ARvwListadoConfiguracionArea> ARvwListadoConfiguracionArea { get; set; }
        public virtual DbSet<ARvwListadoRequisicionMaterial> ARvwListadoRequisicionMaterial { get; set; }
        public virtual DbSet<tblProyecto> tblProyecto { get; set; }
        public virtual DbSet<tblProyecto_Dependencia> tblProyecto_Dependencia { get; set; }
        public virtual DbSet<tblAlmacen> tblAlmacen { get; set; }
        public virtual DbSet<tblObjetoGasto> tblObjetoGasto { get; set; }
        public virtual DbSet<tblRamo> tblRamo { get; set; }
        public virtual DbSet<ARvwListadoRequisicionPorSurtir> ARvwListadoRequisicionPorSurtir { get; set; }
        public virtual DbSet<MItblControlMaestroControlPeriodo> MItblControlMaestroControlPeriodo { get; set; }
        public virtual DbSet<MItblControlMaestroDimension> MItblControlMaestroDimension { get; set; }
        public virtual DbSet<MItblControlMaestroDimensionNivel> MItblControlMaestroDimensionNivel { get; set; }
        public virtual DbSet<MItblControlMaestroTipoIndicador> MItblControlMaestroTipoIndicador { get; set; }
        public virtual DbSet<MItblControlMaestroTipoIndicadorNivel> MItblControlMaestroTipoIndicadorNivel { get; set; }
        public virtual DbSet<MItblControlMaestroUnidadMedida> MItblControlMaestroUnidadMedida { get; set; }
        public virtual DbSet<MItblControlMaestroUnidadMedidaDimension> MItblControlMaestroUnidadMedidaDimension { get; set; }
        public virtual DbSet<MItblControlMaestroUnidadMedidaFormulaVariable> MItblControlMaestroUnidadMedidaFormulaVariable { get; set; }
        public virtual DbSet<MItblMatrizConfiguracionPresupuestal> MItblMatrizConfiguracionPresupuestal { get; set; }
        public virtual DbSet<MItblMatrizIndicadorResultado> MItblMatrizIndicadorResultado { get; set; }
        public virtual DbSet<MItblMatrizIndicadorResultadoIndicadorFormulaVariable> MItblMatrizIndicadorResultadoIndicadorFormulaVariable { get; set; }
        public virtual DbSet<MItblMatrizIndicadorResultadoIndicadorMeta> MItblMatrizIndicadorResultadoIndicadorMeta { get; set; }
        public virtual DbSet<MItblPlanDesarrollo> MItblPlanDesarrollo { get; set; }
        public virtual DbSet<MItblPlanDesarrolloEstructura> MItblPlanDesarrolloEstructura { get; set; }
        public virtual DbSet<MIvwListadoPlanNacionalDesarrollo> MIvwListadoPlanNacionalDesarrollo { get; set; }
        public virtual DbSet<MIvwListadoMatrizConfiguracionPresupuestal> MIvwListadoMatrizConfiguracionPresupuestal { get; set; }
        public virtual DbSet<tblProgramaGobierno> tblProgramaGobierno { get; set; }
        public virtual DbSet<tblProducto> tblProducto { get; set; }
        public virtual DbSet<tblUnidadDeMedida> tblUnidadDeMedida { get; set; }
        public virtual DbSet<GRtblArchivo> GRtblArchivo { get; set; }
        public virtual DbSet<GRtblArchivoEstructuraCarpeta> GRtblArchivoEstructuraCarpeta { get; set; }
        public virtual DbSet<GRtblControlMaestroOrigenArchivo> GRtblControlMaestroOrigenArchivo { get; set; }
        public virtual DbSet<GRtblMenuPrincipal> GRtblMenuPrincipal { get; set; }
        public virtual DbSet<tblCuentaPresupuestalEgr> tblCuentaPresupuestalEgr { get; set; }
        public virtual DbSet<tblTipoGasto> tblTipoGasto { get; set; }
        public virtual DbSet<GRtblAutonumerico> GRtblAutonumerico { get; set; }
        public virtual DbSet<tblDependencia> tblDependencia { get; set; }
        public virtual DbSet<RHtblEmpleado> RHtblEmpleado { get; set; }
        public virtual DbSet<tblProveedor> tblProveedor { get; set; }
        public virtual DbSet<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador { get; set; }
        public virtual DbSet<MItblMatrizConfiguracionPresupuestalSeguimientoVariable> MItblMatrizConfiguracionPresupuestalSeguimientoVariable { get; set; }
        public virtual DbSet<MIvwListadoMatrizConfiguracionPresupuestalSeguimientoVariable> MIvwListadoMatrizConfiguracionPresupuestalSeguimientoVariable { get; set; }
        public virtual DbSet<MItblControlMaestroFrecuenciaMedicion> MItblControlMaestroFrecuenciaMedicion { get; set; }
        public virtual DbSet<MItblControlMaestroFrecuenciaMedicionNivel> MItblControlMaestroFrecuenciaMedicionNivel { get; set; }
        public virtual DbSet<tblOrdenCompra> tblOrdenCompra { get; set; }
        public virtual DbSet<tblOrdenCompraDet> tblOrdenCompraDet { get; set; }
        public virtual DbSet<tblTarifaImpuesto> tblTarifaImpuesto { get; set; }
        public virtual DbSet<ARtblInvitacionCompra> ARtblInvitacionCompra { get; set; }
        public virtual DbSet<ARtblInvitacionCompraDetalle> ARtblInvitacionCompraDetalle { get; set; }
        public virtual DbSet<tblTipoComprobanteFiscal> tblTipoComprobanteFiscal { get; set; }
        public virtual DbSet<tblTipoOperacion> tblTipoOperacion { get; set; }
        public virtual DbSet<ARvwListadoOrdenCompra> ARvwListadoOrdenCompra { get; set; }
        public virtual DbSet<ARvwListadoOrdenCompraRecibo> ARvwListadoOrdenCompraRecibo { get; set; }
        public virtual DbSet<tblCompra> tblCompra { get; set; }
        public virtual DbSet<tblCompraDet> tblCompraDet { get; set; }
        public virtual DbSet<ARtblOrdenCompraRequisicionDet> ARtblOrdenCompraRequisicionDet { get; set; }
        public virtual DbSet<ARtblCompraCancelInfo> ARtblCompraCancelInfo { get; set; }
        public virtual DbSet<ARtblInventarioAjusteDetalle> ARtblInventarioAjusteDetalle { get; set; }
        public virtual DbSet<ARtblControlMaestroConceptoAjusteInventario> ARtblControlMaestroConceptoAjusteInventario { get; set; }
        public virtual DbSet<ARtblInventarioMovimiento> ARtblInventarioMovimiento { get; set; }
        public virtual DbSet<tblPoliza> tblPoliza { get; set; }
        public virtual DbSet<tblSubProgramaGobierno> tblSubProgramaGobierno { get; set; }
        public virtual DbSet<GRtblRol> GRtblRol { get; set; }
        public virtual DbSet<GRtblRolMenu> GRtblRolMenu { get; set; }
        public virtual DbSet<ARtblInvitacionArticulo> ARtblInvitacionArticulo { get; set; }
        public virtual DbSet<ARtblInvitacionArticuloDetalle> ARtblInvitacionArticuloDetalle { get; set; }
        public virtual DbSet<GRvwListadoRol> GRvwListadoRol { get; set; }
        public virtual DbSet<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle { get; set; }
        public virtual DbSet<MIvwComboListadoMIR> MIvwComboListadoMIR { get; set; }
        public virtual DbSet<GRvwListadoUsuario> GRvwListadoUsuario { get; set; }
        public virtual DbSet<GRtblPermisoFicha> GRtblPermisoFicha { get; set; }
        public virtual DbSet<GRtblUsarioPermiso> GRtblUsarioPermiso { get; set; }
        public virtual DbSet<ArtblInvitacionCompraDetallePrecioProveedor> ArtblInvitacionCompraDetallePrecioProveedor { get; set; }
        public virtual DbSet<ARtblInvitacionCompraProveedor> ARtblInvitacionCompraProveedor { get; set; }
        public virtual DbSet<ArtblInvitacionCompraProveedorCotizacion> ArtblInvitacionCompraProveedorCotizacion { get; set; }
        public virtual DbSet<ARvwListadoInvitacionCompra> ARvwListadoInvitacionCompra { get; set; }
        public virtual DbSet<MIvwListadoMIR> MIvwListadoMIR { get; set; }
        public virtual DbSet<ARtblOrdenCompraInvitacionDet> ARtblOrdenCompraInvitacionDet { get; set; }
        public virtual DbSet<ARtblCortesia> ARtblCortesia { get; set; }
        public virtual DbSet<ARtblCortesiaDetalle> ARtblCortesiaDetalle { get; set; }
        public virtual DbSet<ARvwListadoReciboCortesia> ARvwListadoReciboCortesia { get; set; }
        public virtual DbSet<ARtblTransferencia> ARtblTransferencia { get; set; }
        public virtual DbSet<ARtblTransferenciaMovto> ARtblTransferenciaMovto { get; set; }
        public virtual DbSet<ARvwListadoTransferencias> ARvwListadoTransferencias { get; set; }
        public virtual DbSet<ARtblInventarioFisico> ARtblInventarioFisico { get; set; }
        public virtual DbSet<ARvwListadoInventarioFisico> ARvwListadoInventarioFisico { get; set; }
        public virtual DbSet<ARvwListadoInventarioAjuste> ARvwListadoInventarioAjuste { get; set; }
        public virtual DbSet<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion { get; set; }
        public virtual DbSet<GRtblAlerta> GRtblAlerta { get; set; }
        public virtual DbSet<ARtblInventarioMovimientoAgrupador> ARtblInventarioMovimientoAgrupador { get; set; }
        public virtual DbSet<tblAdministracionPeriodo> tblAdministracionPeriodo { get; set; }
    
        public virtual ObjectResult<tblObjetoGasto> spObjetoGasto(string inicial)
        {
            var inicialParameter = inicial != null ?
                new ObjectParameter("Inicial", inicial) :
                new ObjectParameter("Inicial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblObjetoGasto>("spObjetoGasto", inicialParameter);
        }
    
        public virtual ObjectResult<tblObjetoGasto> spObjetoGasto(string inicial, MergeOption mergeOption)
        {
            var inicialParameter = inicial != null ?
                new ObjectParameter("Inicial", inicial) :
                new ObjectParameter("Inicial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblObjetoGasto>("spObjetoGasto", mergeOption, inicialParameter);
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionMaterialProductos_Result> ARspConsultaRequisicionMaterialProductos(string areaId, string unidadAdministrativaId, string proyectoId)
        {
            var areaIdParameter = areaId != null ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(string));
    
            var unidadAdministrativaIdParameter = unidadAdministrativaId != null ?
                new ObjectParameter("unidadAdministrativaId", unidadAdministrativaId) :
                new ObjectParameter("unidadAdministrativaId", typeof(string));
    
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionMaterialProductos_Result>("ARspConsultaRequisicionMaterialProductos", areaIdParameter, unidadAdministrativaIdParameter, proyectoIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionMaterialDetalles_Result> ARspConsultaRequisicionMaterialDetalles(Nullable<int> requisicionId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionMaterialDetalles_Result>("ARspConsultaRequisicionMaterialDetalles", requisicionIdParameter);
        }
    
        public virtual int GRspAutonumericoSigIncr(string nombre, Nullable<int> ejercicio, ObjectParameter valorSalida)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ejercicioParameter = ejercicio.HasValue ?
                new ObjectParameter("ejercicio", ejercicio) :
                new ObjectParameter("ejercicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspAutonumericoSigIncr", nombreParameter, ejercicioParameter, valorSalida);
        }
    
        public virtual ObjectResult<ARspConsultaInventarioAjusteDetalles_Result> ARspConsultaInventarioAjusteDetalles(Nullable<int> inventarioAjusteId)
        {
            var inventarioAjusteIdParameter = inventarioAjusteId.HasValue ?
                new ObjectParameter("inventarioAjusteId", inventarioAjusteId) :
                new ObjectParameter("inventarioAjusteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInventarioAjusteDetalles_Result>("ARspConsultaInventarioAjusteDetalles", inventarioAjusteIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaInventarioFisicoDetalles_Result> ARspConsultaInventarioFisicoDetalles(Nullable<int> inventarioFisicoId)
        {
            var inventarioFisicoIdParameter = inventarioFisicoId.HasValue ?
                new ObjectParameter("inventarioFisicoId", inventarioFisicoId) :
                new ObjectParameter("inventarioFisicoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInventarioFisicoDetalles_Result>("ARspConsultaInventarioFisicoDetalles", inventarioFisicoIdParameter);
        }
    
        public virtual int ARspAfectaInventarioAjuste(Nullable<int> inventarioId, Nullable<int> usuarioId)
        {
            var inventarioIdParameter = inventarioId.HasValue ?
                new ObjectParameter("InventarioId", inventarioId) :
                new ObjectParameter("InventarioId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspAfectaInventarioAjuste", inventarioIdParameter, usuarioIdParameter);
        }
    
        public virtual int ARspAfectaInventarioFisico(Nullable<int> inventarioId, Nullable<int> usuarioId)
        {
            var inventarioIdParameter = inventarioId.HasValue ?
                new ObjectParameter("InventarioId", inventarioId) :
                new ObjectParameter("InventarioId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspAfectaInventarioFisico", inventarioIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaDimensionConNivel_Result> MIspConsultaDimensionConNivel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaDimensionConNivel_Result>("MIspConsultaDimensionConNivel");
        }
    
        public virtual ObjectResult<MIspConsultaTipoIndicadorConNivel_Result> MIspConsultaTipoIndicadorConNivel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaTipoIndicadorConNivel_Result>("MIspConsultaTipoIndicadorConNivel");
        }
    
        public virtual ObjectResult<tblProducto> ARspObjetoGastoAlmacenProductos(string almacenId, string objetoGastoId)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            var objetoGastoIdParameter = objetoGastoId != null ?
                new ObjectParameter("objetoGastoId", objetoGastoId) :
                new ObjectParameter("objetoGastoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblProducto>("ARspObjetoGastoAlmacenProductos", almacenIdParameter, objetoGastoIdParameter);
        }
    
        public virtual ObjectResult<tblProducto> ARspObjetoGastoAlmacenProductos(string almacenId, string objetoGastoId, MergeOption mergeOption)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            var objetoGastoIdParameter = objetoGastoId != null ?
                new ObjectParameter("objetoGastoId", objetoGastoId) :
                new ObjectParameter("objetoGastoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblProducto>("ARspObjetoGastoAlmacenProductos", mergeOption, almacenIdParameter, objetoGastoIdParameter);
        }
    
        public virtual ObjectResult<ARspListadoProductosPorAlmacenId_Result> ARspListadoProductosPorAlmacenId(string almacenId)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspListadoProductosPorAlmacenId_Result>("ARspListadoProductosPorAlmacenId", almacenIdParameter);
        }
    
        public virtual ObjectResult<string> GRspAutonumericoArcSigIncr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GRspAutonumericoArcSigIncr");
        }
    
        public virtual ObjectResult<MIspRep_Proyecto_Result> MIspRep_Proyecto(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string where)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("fechaIni", fechaIni) :
                new ObjectParameter("fechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var whereParameter = where != null ?
                new ObjectParameter("where", where) :
                new ObjectParameter("where", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspRep_Proyecto_Result>("MIspRep_Proyecto", fechaIniParameter, fechaFinParameter, whereParameter);
        }
    
        public virtual ObjectResult<string> RHspGetNombreCompletoEmpleado(Nullable<int> empleadoId)
        {
            var empleadoIdParameter = empleadoId.HasValue ?
                new ObjectParameter("empleadoId", empleadoId) :
                new ObjectParameter("empleadoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RHspGetNombreCompletoEmpleado", empleadoIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaConfiguracionAreaProyectos_Result> ARspConsultaConfiguracionAreaProyectos(Nullable<int> configuracionAreaId)
        {
            var configuracionAreaIdParameter = configuracionAreaId.HasValue ?
                new ObjectParameter("configuracionAreaId", configuracionAreaId) :
                new ObjectParameter("configuracionAreaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaConfiguracionAreaProyectos_Result>("ARspConsultaConfiguracionAreaProyectos", configuracionAreaIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaConfiguracionAreaAlmacenes_Result> ARspConsultaConfiguracionAreaAlmacenes(Nullable<int> configuracionAreaId)
        {
            var configuracionAreaIdParameter = configuracionAreaId.HasValue ?
                new ObjectParameter("configuracionAreaId", configuracionAreaId) :
                new ObjectParameter("configuracionAreaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaConfiguracionAreaAlmacenes_Result>("ARspConsultaConfiguracionAreaAlmacenes", configuracionAreaIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaUnidadMedidaConDimension_Result> MIspConsultaUnidadMedidaConDimension()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaUnidadMedidaConDimension_Result>("MIspConsultaUnidadMedidaConDimension");
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionPorComprarDetalles_Result> ARspConsultaRequisicionPorComprarDetalles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionPorComprarDetalles_Result>("ARspConsultaRequisicionPorComprarDetalles");
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionPorSurtirDetalles_Result> ARspConsultaRequisicionPorSurtirDetalles(Nullable<int> requisicionId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionPorSurtirDetalles_Result>("ARspConsultaRequisicionPorSurtirDetalles", requisicionIdParameter);
        }
    
        public virtual ObjectResult<string> GRspGetFechaConFormato(Nullable<System.DateTime> date, Nullable<bool> mostrarHoras)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var mostrarHorasParameter = mostrarHoras.HasValue ?
                new ObjectParameter("mostrarHoras", mostrarHoras) :
                new ObjectParameter("mostrarHoras", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GRspGetFechaConFormato", dateParameter, mostrarHorasParameter);
        }
    
        public virtual int ARspActualizaEstatusRequisicionMaterial(Nullable<int> requisicionId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspActualizaEstatusRequisicionMaterial", requisicionIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionPorComprarFuentesFinanciamiento_Result> ARspConsultaRequisicionPorComprarFuentesFinanciamiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionPorComprarFuentesFinanciamiento_Result>("ARspConsultaRequisicionPorComprarFuentesFinanciamiento");
        }
    
        public virtual ObjectResult<ARspConsultaRequisicionPorSurtirExistencias_Result> ARspConsultaRequisicionPorSurtirExistencias(Nullable<int> requisicionId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaRequisicionPorSurtirExistencias_Result>("ARspConsultaRequisicionPorSurtirExistencias", requisicionIdParameter);
        }
    
        public virtual int ARspRequisicionMaterialAutorizar(Nullable<int> requisicionId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspRequisicionMaterialAutorizar", requisicionIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaFrecuenciaMedicionConNivel_Result> MIspConsultaFrecuenciaMedicionConNivel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaFrecuenciaMedicionConNivel_Result>("MIspConsultaFrecuenciaMedicionConNivel");
        }
    
        public virtual int ARspActualizaEstatusOrdenCompra(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("ordenCompraId", ordenCompraId) :
                new ObjectParameter("ordenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspActualizaEstatusOrdenCompra", ordenCompraIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaDatosFinanciamientoOrdenCompra_Result> ARspConsultaDatosFinanciamientoOrdenCompra(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("ordenCompraId", ordenCompraId) :
                new ObjectParameter("ordenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaDatosFinanciamientoOrdenCompra_Result>("ARspConsultaDatosFinanciamientoOrdenCompra", ordenCompraIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaOrdenCompraProductos_Result> ARspConsultaOrdenCompraProductos(string almacenId, string dependenciaId, string proyectoId, string ramoId)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            var dependenciaIdParameter = dependenciaId != null ?
                new ObjectParameter("dependenciaId", dependenciaId) :
                new ObjectParameter("dependenciaId", typeof(string));
    
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(string));
    
            var ramoIdParameter = ramoId != null ?
                new ObjectParameter("ramoId", ramoId) :
                new ObjectParameter("ramoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaOrdenCompraProductos_Result>("ARspConsultaOrdenCompraProductos", almacenIdParameter, dependenciaIdParameter, proyectoIdParameter, ramoIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaOCPorRecibirDetalles_Result> ARspConsultaOCPorRecibirDetalles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaOCPorRecibirDetalles_Result>("ARspConsultaOCPorRecibirDetalles");
        }
    
        public virtual ObjectResult<ARspConsultaDatosOCReciboPorId_Result> ARspConsultaDatosOCReciboPorId(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("ordenCompraId", ordenCompraId) :
                new ObjectParameter("ordenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaDatosOCReciboPorId_Result>("ARspConsultaDatosOCReciboPorId", ordenCompraIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionArticulosPorConvertir_Result> ARspConsultaInvitacionArticulosPorConvertir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionArticulosPorConvertir_Result>("ARspConsultaInvitacionArticulosPorConvertir");
        }
    
        public virtual ObjectResult<RHspConsultaEmpleadoLigado_Result> RHspConsultaEmpleadoLigado(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RHspConsultaEmpleadoLigado_Result>("RHspConsultaEmpleadoLigado", usuarioIdParameter);
        }
    
        public virtual ObjectResult<GRspArbolPermisoFicha_Result> GRspArbolPermisoFicha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRspArbolPermisoFicha_Result>("GRspArbolPermisoFicha");
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionCompraDetallePreciosProveedores_Result> ARspConsultaInvitacionCompraDetallePreciosProveedores(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionCompraDetallePreciosProveedores_Result>("ARspConsultaInvitacionCompraDetallePreciosProveedores", invitacionIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionCompraDetalles_Result> ARspConsultaInvitacionCompraDetalles(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionCompraDetalles_Result>("ARspConsultaInvitacionCompraDetalles", invitacionIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionCompraListadoProveedores_Result> ARspConsultaInvitacionCompraListadoProveedores(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionCompraListadoProveedores_Result>("ARspConsultaInvitacionCompraListadoProveedores", invitacionIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionCompraProveedorCotizaciones_Result> ARspConsultaInvitacionCompraProveedorCotizaciones(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionCompraProveedorCotizaciones_Result>("ARspConsultaInvitacionCompraProveedorCotizaciones", invitacionIdParameter);
        }
    
        public virtual ObjectResult<spComboProgramaGobierno_Result> spComboProgramaGobierno(string programaPresupuestarioId)
        {
            var programaPresupuestarioIdParameter = programaPresupuestarioId != null ?
                new ObjectParameter("ProgramaPresupuestarioId", programaPresupuestarioId) :
                new ObjectParameter("ProgramaPresupuestarioId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spComboProgramaGobierno_Result>("spComboProgramaGobierno", programaPresupuestarioIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaCortesiaDetalles_Result> ARspConsultaCortesiaDetalles(Nullable<int> cortesiaId)
        {
            var cortesiaIdParameter = cortesiaId.HasValue ?
                new ObjectParameter("cortesiaId", cortesiaId) :
                new ObjectParameter("cortesiaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaCortesiaDetalles_Result>("ARspConsultaCortesiaDetalles", cortesiaIdParameter);
        }
    
        public virtual int ARspAfectaReciboCortesia(Nullable<int> cortesiaId, Nullable<int> usuarioId)
        {
            var cortesiaIdParameter = cortesiaId.HasValue ?
                new ObjectParameter("CortesiaId", cortesiaId) :
                new ObjectParameter("CortesiaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspAfectaReciboCortesia", cortesiaIdParameter, usuarioIdParameter);
        }
    
        public virtual int MIspConsultaFormulaConDimension()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MIspConsultaFormulaConDimension");
        }
    
        public virtual int MIspConsultaPlanDesarrolloEstructuras(Nullable<int> planDesarrolloId)
        {
            var planDesarrolloIdParameter = planDesarrolloId.HasValue ?
                new ObjectParameter("planDesarrolloId", planDesarrolloId) :
                new ObjectParameter("planDesarrolloId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MIspConsultaPlanDesarrolloEstructuras", planDesarrolloIdParameter);
        }
    
        public virtual ObjectResult<MIspRptLibroConsultaPlanDesarrolloEstructura_Result> MIspRptLibroConsultaPlanDesarrolloEstructura(Nullable<int> planDesarrolloEstructuraId)
        {
            var planDesarrolloEstructuraIdParameter = planDesarrolloEstructuraId.HasValue ?
                new ObjectParameter("PlanDesarrolloEstructuraId", planDesarrolloEstructuraId) :
                new ObjectParameter("PlanDesarrolloEstructuraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspRptLibroConsultaPlanDesarrolloEstructura_Result>("MIspRptLibroConsultaPlanDesarrolloEstructura", planDesarrolloEstructuraIdParameter);
        }
    
        public virtual int ARspAfectaTransferencias(Nullable<int> transferenciaId, Nullable<int> usuarioId)
        {
            var transferenciaIdParameter = transferenciaId.HasValue ?
                new ObjectParameter("TransferenciaId", transferenciaId) :
                new ObjectParameter("TransferenciaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspAfectaTransferencias", transferenciaIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaTransferenciaDetalles_Result> ARspConsultaTransferenciaDetalles(Nullable<int> transferenciaId)
        {
            var transferenciaIdParameter = transferenciaId.HasValue ?
                new ObjectParameter("transferenciaId", transferenciaId) :
                new ObjectParameter("transferenciaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaTransferenciaDetalles_Result>("ARspConsultaTransferenciaDetalles", transferenciaIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaTransferenciaProductos_Result> ARspConsultaTransferenciaProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaTransferenciaProductos_Result>("ARspConsultaTransferenciaProductos");
        }
    
        public virtual ObjectResult<ARspConsultaInvitacionCompraOrdenesCompra_Result> ARspConsultaInvitacionCompraOrdenesCompra(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaInvitacionCompraOrdenesCompra_Result>("ARspConsultaInvitacionCompraOrdenesCompra", invitacionIdParameter);
        }
    
        public virtual ObjectResult<spObtenerFechaDelServidor_Result> spObtenerFechaDelServidor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerFechaDelServidor_Result>("spObtenerFechaDelServidor");
        }
    
        public virtual ObjectResult<GRspConsultaMenuPrincipalPermiso_Result> GRspConsultaMenuPrincipalPermiso(Nullable<int> rolId)
        {
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRspConsultaMenuPrincipalPermiso_Result>("GRspConsultaMenuPrincipalPermiso", rolIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaMatrizIndicadorResultado_Result> MIspConsultaMatrizIndicadorResultado(Nullable<int> mirId)
        {
            var mirIdParameter = mirId.HasValue ?
                new ObjectParameter("mirId", mirId) :
                new ObjectParameter("mirId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaMatrizIndicadorResultado_Result>("MIspConsultaMatrizIndicadorResultado", mirIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaRepProyecto_Result> MIspConsultaRepProyecto(string proyectoIds, string anio)
        {
            var proyectoIdsParameter = proyectoIds != null ?
                new ObjectParameter("ProyectoIds", proyectoIds) :
                new ObjectParameter("ProyectoIds", typeof(string));
    
            var anioParameter = anio != null ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaRepProyecto_Result>("MIspConsultaRepProyecto", proyectoIdsParameter, anioParameter);
        }
    
        public virtual int ARspActualizaEstatusInvitacionCompra(Nullable<int> invitacionId)
        {
            var invitacionIdParameter = invitacionId.HasValue ?
                new ObjectParameter("invitacionId", invitacionId) :
                new ObjectParameter("invitacionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspActualizaEstatusInvitacionCompra", invitacionIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaOrdenCompraReciboDetalles_Result> ARspConsultaOrdenCompraReciboDetalles(Nullable<int> compraId)
        {
            var compraIdParameter = compraId.HasValue ?
                new ObjectParameter("compraId", compraId) :
                new ObjectParameter("compraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaOrdenCompraReciboDetalles_Result>("ARspConsultaOrdenCompraReciboDetalles", compraIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaOrdenCompraDetalles_Result> ARspConsultaOrdenCompraDetalles(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("ordenCompraId", ordenCompraId) :
                new ObjectParameter("ordenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaOrdenCompraDetalles_Result>("ARspConsultaOrdenCompraDetalles", ordenCompraIdParameter);
        }
    
        public virtual ObjectResult<GRspAlertasConfiguracionEmpleados_Result> GRspAlertasConfiguracionEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRspAlertasConfiguracionEmpleados_Result>("GRspAlertasConfiguracionEmpleados");
        }
    
        public virtual ObjectResult<GRspAlertasConfiguracionMenuPrincipal_Result> GRspAlertasConfiguracionMenuPrincipal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRspAlertasConfiguracionMenuPrincipal_Result>("GRspAlertasConfiguracionMenuPrincipal");
        }
    
        public virtual ObjectResult<string> ARspCargaInventarioInicialValidarFila(string productoId, string almacenId, string fuenteFinanciamientoId, string proyectoId, string unidadAdministrativaId, string tipoGastoId, Nullable<decimal> cantidad, Nullable<decimal> costoUnitario)
        {
            var productoIdParameter = productoId != null ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(string));
    
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("AlmacenId", almacenId) :
                new ObjectParameter("AlmacenId", typeof(string));
    
            var fuenteFinanciamientoIdParameter = fuenteFinanciamientoId != null ?
                new ObjectParameter("FuenteFinanciamientoId", fuenteFinanciamientoId) :
                new ObjectParameter("FuenteFinanciamientoId", typeof(string));
    
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(string));
    
            var unidadAdministrativaIdParameter = unidadAdministrativaId != null ?
                new ObjectParameter("UnidadAdministrativaId", unidadAdministrativaId) :
                new ObjectParameter("UnidadAdministrativaId", typeof(string));
    
            var tipoGastoIdParameter = tipoGastoId != null ?
                new ObjectParameter("TipoGastoId", tipoGastoId) :
                new ObjectParameter("TipoGastoId", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var costoUnitarioParameter = costoUnitario.HasValue ?
                new ObjectParameter("CostoUnitario", costoUnitario) :
                new ObjectParameter("CostoUnitario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ARspCargaInventarioInicialValidarFila", productoIdParameter, almacenIdParameter, fuenteFinanciamientoIdParameter, proyectoIdParameter, unidadAdministrativaIdParameter, tipoGastoIdParameter, cantidadParameter, costoUnitarioParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptExistenciasPartidas")]
        public virtual IQueryable<ARfnRptExistenciasPartidas_Result> ARfnRptExistenciasPartidas(string objetoGastoId, Nullable<int> usuarioId)
        {
            var objetoGastoIdParameter = objetoGastoId != null ?
                new ObjectParameter("objetoGastoId", objetoGastoId) :
                new ObjectParameter("objetoGastoId", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptExistenciasPartidas_Result>("[SAACGContext].[ARfnRptExistenciasPartidas](@objetoGastoId, @usuarioId)", objetoGastoIdParameter, usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptExistenciasPresupuestales")]
        public virtual IQueryable<ARfnRptExistenciasPresupuestales_Result> ARfnRptExistenciasPresupuestales(string unidadAdministrativaId, string proyectoId, string fuenteFinanciamientoId, string tipoGastoId, Nullable<int> usuarioId)
        {
            var unidadAdministrativaIdParameter = unidadAdministrativaId != null ?
                new ObjectParameter("unidadAdministrativaId", unidadAdministrativaId) :
                new ObjectParameter("unidadAdministrativaId", typeof(string));
    
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(string));
    
            var fuenteFinanciamientoIdParameter = fuenteFinanciamientoId != null ?
                new ObjectParameter("fuenteFinanciamientoId", fuenteFinanciamientoId) :
                new ObjectParameter("fuenteFinanciamientoId", typeof(string));
    
            var tipoGastoIdParameter = tipoGastoId != null ?
                new ObjectParameter("tipoGastoId", tipoGastoId) :
                new ObjectParameter("tipoGastoId", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptExistenciasPresupuestales_Result>("[SAACGContext].[ARfnRptExistenciasPresupuestales](@unidadAdministrativaId, @proyectoId, @fuenteFinanciamientoId, @tipoGastoId, @usuarioId)", unidadAdministrativaIdParameter, proyectoIdParameter, fuenteFinanciamientoIdParameter, tipoGastoIdParameter, usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptExistenciasTotales")]
        public virtual IQueryable<ARfnRptExistenciasTotales_Result> ARfnRptExistenciasTotales(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptExistenciasTotales_Result>("[SAACGContext].[ARfnRptExistenciasTotales](@usuarioId)", usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptKardex")]
        public virtual IQueryable<ARfnRptKardex_Result> ARfnRptKardex(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> tipoMvtoId, Nullable<int> mvtoId, Nullable<int> polizaId, string almacenId, string productoId, string unidadAdministrativaId, string proyectoId, string fuenteFinanciamientoId, Nullable<int> usuarioId)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var tipoMvtoIdParameter = tipoMvtoId.HasValue ?
                new ObjectParameter("tipoMvtoId", tipoMvtoId) :
                new ObjectParameter("tipoMvtoId", typeof(int));
    
            var mvtoIdParameter = mvtoId.HasValue ?
                new ObjectParameter("mvtoId", mvtoId) :
                new ObjectParameter("mvtoId", typeof(int));
    
            var polizaIdParameter = polizaId.HasValue ?
                new ObjectParameter("polizaId", polizaId) :
                new ObjectParameter("polizaId", typeof(int));
    
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            var productoIdParameter = productoId != null ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(string));
    
            var unidadAdministrativaIdParameter = unidadAdministrativaId != null ?
                new ObjectParameter("unidadAdministrativaId", unidadAdministrativaId) :
                new ObjectParameter("unidadAdministrativaId", typeof(string));
    
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(string));
    
            var fuenteFinanciamientoIdParameter = fuenteFinanciamientoId != null ?
                new ObjectParameter("fuenteFinanciamientoId", fuenteFinanciamientoId) :
                new ObjectParameter("fuenteFinanciamientoId", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptKardex_Result>("[SAACGContext].[ARfnRptKardex](@fechaInicio, @fechaFin, @tipoMvtoId, @mvtoId, @polizaId, @almacenId, @productoId, @unidadAdministrativaId, @proyectoId, @fuenteFinanciamientoId, @usuarioId)", fechaInicioParameter, fechaFinParameter, tipoMvtoIdParameter, mvtoIdParameter, polizaIdParameter, almacenIdParameter, productoIdParameter, unidadAdministrativaIdParameter, proyectoIdParameter, fuenteFinanciamientoIdParameter, usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptLibroAlmacen")]
        public virtual IQueryable<ARfnRptLibroAlmacen_Result> ARfnRptLibroAlmacen(string almacenId)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptLibroAlmacen_Result>("[SAACGContext].[ARfnRptLibroAlmacen](@almacenId)", almacenIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptSolicitudMateriales")]
        public virtual IQueryable<ARfnRptSolicitudMateriales_Result> ARfnRptSolicitudMateriales(Nullable<int> requisicionId, Nullable<int> usuarioId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptSolicitudMateriales_Result>("[SAACGContext].[ARfnRptSolicitudMateriales](@requisicionId, @usuarioId)", requisicionIdParameter, usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptSurtidoSolicitud")]
        public virtual IQueryable<ARfnRptSurtidoSolicitud_Result> ARfnRptSurtidoSolicitud(Nullable<int> requisicionId, Nullable<int> usuarioId)
        {
            var requisicionIdParameter = requisicionId.HasValue ?
                new ObjectParameter("requisicionId", requisicionId) :
                new ObjectParameter("requisicionId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptSurtidoSolicitud_Result>("[SAACGContext].[ARfnRptSurtidoSolicitud](@requisicionId, @usuarioId)", requisicionIdParameter, usuarioIdParameter);
        }
    
        [DbFunction("SAACGContext", "ARfnRptSurtimientoOC")]
        public virtual IQueryable<ARfnRptSurtimientoOC_Result> ARfnRptSurtimientoOC(Nullable<int> reciboId, Nullable<int> usuarioId)
        {
            var reciboIdParameter = reciboId.HasValue ?
                new ObjectParameter("reciboId", reciboId) :
                new ObjectParameter("reciboId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ARfnRptSurtimientoOC_Result>("[SAACGContext].[ARfnRptSurtimientoOC](@reciboId, @usuarioId)", reciboIdParameter, usuarioIdParameter);
        }
    
        public virtual int ARspCargaInventarioInicial(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspCargaInventarioInicial", usuarioIdParameter);
        }
    
        public virtual int ARspProcesadorInventarios(Nullable<int> tipoMovimientoId, string motivoMovto, Nullable<int> creadoPorId, Nullable<bool> insertarAgrupador, Nullable<int> referenciaMovtoId, Nullable<int> polizaId)
        {
            var tipoMovimientoIdParameter = tipoMovimientoId.HasValue ?
                new ObjectParameter("TipoMovimientoId", tipoMovimientoId) :
                new ObjectParameter("TipoMovimientoId", typeof(int));
    
            var motivoMovtoParameter = motivoMovto != null ?
                new ObjectParameter("MotivoMovto", motivoMovto) :
                new ObjectParameter("MotivoMovto", typeof(string));
    
            var creadoPorIdParameter = creadoPorId.HasValue ?
                new ObjectParameter("CreadoPorId", creadoPorId) :
                new ObjectParameter("CreadoPorId", typeof(int));
    
            var insertarAgrupadorParameter = insertarAgrupador.HasValue ?
                new ObjectParameter("InsertarAgrupador", insertarAgrupador) :
                new ObjectParameter("InsertarAgrupador", typeof(bool));
    
            var referenciaMovtoIdParameter = referenciaMovtoId.HasValue ?
                new ObjectParameter("ReferenciaMovtoId", referenciaMovtoId) :
                new ObjectParameter("ReferenciaMovtoId", typeof(int));
    
            var polizaIdParameter = polizaId.HasValue ?
                new ObjectParameter("PolizaId", polizaId) :
                new ObjectParameter("PolizaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARspProcesadorInventarios", tipoMovimientoIdParameter, motivoMovtoParameter, creadoPorIdParameter, insertarAgrupadorParameter, referenciaMovtoIdParameter, polizaIdParameter);
        }
    
        public virtual ObjectResult<ARspConsultaExistenciaAlmacen_Result> ARspConsultaExistenciaAlmacen(string almacenId, string productosIds)
        {
            var almacenIdParameter = almacenId != null ?
                new ObjectParameter("almacenId", almacenId) :
                new ObjectParameter("almacenId", typeof(string));
    
            var productosIdsParameter = productosIds != null ?
                new ObjectParameter("productosIds", productosIds) :
                new ObjectParameter("productosIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaExistenciaAlmacen_Result>("ARspConsultaExistenciaAlmacen", almacenIdParameter, productosIdsParameter);
        }
    
        public virtual int GRspIniciarAlerta(Nullable<int> accionId, Nullable<int> alertaDefinicionId, Nullable<int> referenciaProcesoId, string codigoTramite, string textoRepresentativo, Nullable<int> creadoPorId, ObjectParameter valorSalida)
        {
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(int));
    
            var alertaDefinicionIdParameter = alertaDefinicionId.HasValue ?
                new ObjectParameter("alertaDefinicionId", alertaDefinicionId) :
                new ObjectParameter("alertaDefinicionId", typeof(int));
    
            var referenciaProcesoIdParameter = referenciaProcesoId.HasValue ?
                new ObjectParameter("referenciaProcesoId", referenciaProcesoId) :
                new ObjectParameter("referenciaProcesoId", typeof(int));
    
            var codigoTramiteParameter = codigoTramite != null ?
                new ObjectParameter("codigoTramite", codigoTramite) :
                new ObjectParameter("codigoTramite", typeof(string));
    
            var textoRepresentativoParameter = textoRepresentativo != null ?
                new ObjectParameter("textoRepresentativo", textoRepresentativo) :
                new ObjectParameter("textoRepresentativo", typeof(string));
    
            var creadoPorIdParameter = creadoPorId.HasValue ?
                new ObjectParameter("creadoPorId", creadoPorId) :
                new ObjectParameter("creadoPorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspIniciarAlerta", accionIdParameter, alertaDefinicionIdParameter, referenciaProcesoIdParameter, codigoTramiteParameter, textoRepresentativoParameter, creadoPorIdParameter, valorSalida);
        }
    
        public virtual ObjectResult<MIspRptLibroConsultaMatrizIndicadorResultado_Result> MIspRptLibroConsultaMatrizIndicadorResultado(Nullable<int> mIRId)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspRptLibroConsultaMatrizIndicadorResultado_Result>("MIspRptLibroConsultaMatrizIndicadorResultado", mIRIdParameter);
        }
    
        public virtual int GRspPermiteEliminarRegistro(Nullable<long> registroId, string nombreTabla, ObjectParameter permiteEliminar)
        {
            var registroIdParameter = registroId.HasValue ?
                new ObjectParameter("RegistroId", registroId) :
                new ObjectParameter("RegistroId", typeof(long));
    
            var nombreTablaParameter = nombreTabla != null ?
                new ObjectParameter("NombreTabla", nombreTabla) :
                new ObjectParameter("NombreTabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspPermiteEliminarRegistro", registroIdParameter, nombreTablaParameter, permiteEliminar);
        }
    
        public virtual ObjectResult<GRspGetListadoAlertasPorUsuario_Result> GRspGetListadoAlertasPorUsuario(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRspGetListadoAlertasPorUsuario_Result>("GRspGetListadoAlertasPorUsuario", usuarioIdParameter);
        }
    
        public virtual int GRspAutorizarAlerta(Nullable<int> accionId, Nullable<int> creadoPorId, Nullable<long> alertaId, ObjectParameter valorSalida)
        {
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(int));
    
            var creadoPorIdParameter = creadoPorId.HasValue ?
                new ObjectParameter("creadoPorId", creadoPorId) :
                new ObjectParameter("creadoPorId", typeof(int));
    
            var alertaIdParameter = alertaId.HasValue ?
                new ObjectParameter("alertaId", alertaId) :
                new ObjectParameter("alertaId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspAutorizarAlerta", accionIdParameter, creadoPorIdParameter, alertaIdParameter, valorSalida);
        }
    
        public virtual int GRspOcultarAlertas(Nullable<int> accionId, Nullable<int> creadoPorId, string alertasId, ObjectParameter valorSalida)
        {
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(int));
    
            var creadoPorIdParameter = creadoPorId.HasValue ?
                new ObjectParameter("creadoPorId", creadoPorId) :
                new ObjectParameter("creadoPorId", typeof(int));
    
            var alertasIdParameter = alertasId != null ?
                new ObjectParameter("alertasId", alertasId) :
                new ObjectParameter("alertasId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspOcultarAlertas", accionIdParameter, creadoPorIdParameter, alertasIdParameter, valorSalida);
        }
    
        public virtual int GRspRevisionRechazarAlerta(Nullable<int> accionId, Nullable<int> creadoPorId, Nullable<long> alertaId, string motivo, ObjectParameter valorSalida)
        {
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(int));
    
            var creadoPorIdParameter = creadoPorId.HasValue ?
                new ObjectParameter("creadoPorId", creadoPorId) :
                new ObjectParameter("creadoPorId", typeof(int));
    
            var alertaIdParameter = alertaId.HasValue ?
                new ObjectParameter("alertaId", alertaId) :
                new ObjectParameter("alertaId", typeof(long));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("motivo", motivo) :
                new ObjectParameter("motivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRspRevisionRechazarAlerta", accionIdParameter, creadoPorIdParameter, alertaIdParameter, motivoParameter, valorSalida);
        }
    
        public virtual ObjectResult<ARspConsultaOCPorRecibir_Result> ARspConsultaOCPorRecibir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARspConsultaOCPorRecibir_Result>("ARspConsultaOCPorRecibir");
        }
    
        public virtual ObjectResult<Nullable<int>> ARspValidarRequisicionOC(Nullable<int> ocId)
        {
            var ocIdParameter = ocId.HasValue ?
                new ObjectParameter("ocId", ocId) :
                new ObjectParameter("ocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ARspValidarRequisicionOC", ocIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaPresupuestoVigente_Result> MIspConsultaPresupuestoVigente(Nullable<int> mIRId, string ejercicio)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            var ejercicioParameter = ejercicio != null ?
                new ObjectParameter("Ejercicio", ejercicio) :
                new ObjectParameter("Ejercicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaPresupuestoVigente_Result>("MIspConsultaPresupuestoVigente", mIRIdParameter, ejercicioParameter);
        }
    
        [DbFunction("SAACGContext", "MIfnObtenerSeguimientoIndicadorDesempenio")]
        public virtual IQueryable<MIfnObtenerSeguimientoIndicadorDesempenio_Result> MIfnObtenerSeguimientoIndicadorDesempenio(Nullable<int> mIRIndicadorId)
        {
            var mIRIndicadorIdParameter = mIRIndicadorId.HasValue ?
                new ObjectParameter("MIRIndicadorId", mIRIndicadorId) :
                new ObjectParameter("MIRIndicadorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIfnObtenerSeguimientoIndicadorDesempenio_Result>("[SAACGContext].[MIfnObtenerSeguimientoIndicadorDesempenio](@MIRIndicadorId)", mIRIndicadorIdParameter);
        }
    
        [DbFunction("SAACGContext", "MIfnRptFichaTecnicaIndicador")]
        public virtual IQueryable<MIfnRptFichaTecnicaIndicador_Result> MIfnRptFichaTecnicaIndicador(Nullable<int> mIRId)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIfnRptFichaTecnicaIndicador_Result>("[SAACGContext].[MIfnRptFichaTecnicaIndicador](@MIRId)", mIRIdParameter);
        }
    
        public virtual ObjectResult<MIspConsultaListaVariableIndicador_Result> MIspConsultaListaVariableIndicador(Nullable<int> mIRId)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspConsultaListaVariableIndicador_Result>("MIspConsultaListaVariableIndicador", mIRIdParameter);
        }
    
        public virtual ObjectResult<MIspRptLibroConsultaListaMatrizIndicadorResultado_Result> MIspRptLibroConsultaListaMatrizIndicadorResultado(Nullable<int> mIRId)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspRptLibroConsultaListaMatrizIndicadorResultado_Result>("MIspRptLibroConsultaListaMatrizIndicadorResultado", mIRIdParameter);
        }
    
        public virtual ObjectResult<MIspRptLibroConsultaMatrizIndicadorResultadoIndicador_Result> MIspRptLibroConsultaMatrizIndicadorResultadoIndicador(Nullable<int> mIRId)
        {
            var mIRIdParameter = mIRId.HasValue ?
                new ObjectParameter("MIRId", mIRId) :
                new ObjectParameter("MIRId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIspRptLibroConsultaMatrizIndicadorResultadoIndicador_Result>("MIspRptLibroConsultaMatrizIndicadorResultadoIndicador", mIRIdParameter);
        }
    }
}
