//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRtblUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRtblUsuario()
        {
            this.ARtblAlmacenProductoes = new HashSet<ARtblAlmacenProducto>();
            this.ARtblAlmacenProductoes1 = new HashSet<ARtblAlmacenProducto>();
            this.ARtblControlMaestroConfiguracionAreas = new HashSet<ARtblControlMaestroConfiguracionArea>();
            this.ARtblControlMaestroConfiguracionAreas1 = new HashSet<ARtblControlMaestroConfiguracionArea>();
            this.ARtblControlMaestroConfiguracionAreaAlmacens = new HashSet<ARtblControlMaestroConfiguracionAreaAlmacen>();
            this.ARtblControlMaestroConfiguracionAreaAlmacens1 = new HashSet<ARtblControlMaestroConfiguracionAreaAlmacen>();
            this.ARtblControlMaestroConfiguracionAreaProyectoes = new HashSet<ARtblControlMaestroConfiguracionAreaProyecto>();
            this.ARtblControlMaestroConfiguracionAreaProyectoes1 = new HashSet<ARtblControlMaestroConfiguracionAreaProyecto>();
            this.ARtblControlMaestroConfiguracionMontoCompras = new HashSet<ARtblControlMaestroConfiguracionMontoCompra>();
            this.ARtblControlMaestroConfiguracionMontoCompras1 = new HashSet<ARtblControlMaestroConfiguracionMontoCompra>();
            this.ARtblInventarioAjustes = new HashSet<ARtblInventarioAjuste>();
            this.ARtblInventarioFisicoDetalles = new HashSet<ARtblInventarioFisicoDetalle>();
            this.ARtblInventarioFisicoDetalles1 = new HashSet<ARtblInventarioFisicoDetalle>();
            this.ARtblProveedorProspectoes = new HashSet<ARtblProveedorProspecto>();
            this.ARtblProveedorProspectoes1 = new HashSet<ARtblProveedorProspecto>();
            this.ARtblRequisicionMaterials = new HashSet<ARtblRequisicionMaterial>();
            this.ARtblRequisicionMaterials1 = new HashSet<ARtblRequisicionMaterial>();
            this.ARtblRequisicionMaterialDetalles = new HashSet<ARtblRequisicionMaterialDetalle>();
            this.ARtblRequisicionMaterialDetalles1 = new HashSet<ARtblRequisicionMaterialDetalle>();
            this.MItblControlMaestroControlPeriodo = new HashSet<MItblControlMaestroControlPeriodo>();
            this.MItblControlMaestroControlPeriodo1 = new HashSet<MItblControlMaestroControlPeriodo>();
            this.MItblControlMaestroDimension = new HashSet<MItblControlMaestroDimension>();
            this.MItblControlMaestroDimension1 = new HashSet<MItblControlMaestroDimension>();
            this.MItblControlMaestroDimensionNivel = new HashSet<MItblControlMaestroDimensionNivel>();
            this.MItblControlMaestroDimensionNivel1 = new HashSet<MItblControlMaestroDimensionNivel>();
            this.MItblControlMaestroTipoIndicador = new HashSet<MItblControlMaestroTipoIndicador>();
            this.MItblControlMaestroTipoIndicador1 = new HashSet<MItblControlMaestroTipoIndicador>();
            this.MItblControlMaestroTipoIndicadorNivel = new HashSet<MItblControlMaestroTipoIndicadorNivel>();
            this.MItblControlMaestroTipoIndicadorNivel1 = new HashSet<MItblControlMaestroTipoIndicadorNivel>();
            this.MItblControlMaestroUnidadMedida = new HashSet<MItblControlMaestroUnidadMedida>();
            this.MItblControlMaestroUnidadMedida1 = new HashSet<MItblControlMaestroUnidadMedida>();
            this.MItblControlMaestroUnidadMedidaDimension = new HashSet<MItblControlMaestroUnidadMedidaDimension>();
            this.MItblControlMaestroUnidadMedidaDimension1 = new HashSet<MItblControlMaestroUnidadMedidaDimension>();
            this.MItblControlMaestroUnidadMedidaFormulaVariable = new HashSet<MItblControlMaestroUnidadMedidaFormulaVariable>();
            this.MItblControlMaestroUnidadMedidaFormulaVariable1 = new HashSet<MItblControlMaestroUnidadMedidaFormulaVariable>();
            this.MItblMatrizConfiguracionPresupuestal = new HashSet<MItblMatrizConfiguracionPresupuestal>();
            this.MItblMatrizConfiguracionPresupuestal1 = new HashSet<MItblMatrizConfiguracionPresupuestal>();
            this.MItblMatrizIndicadorResultado = new HashSet<MItblMatrizIndicadorResultado>();
            this.MItblMatrizIndicadorResultado1 = new HashSet<MItblMatrizIndicadorResultado>();
            this.MItblMatrizIndicadorResultadoIndicadorMeta = new HashSet<MItblMatrizIndicadorResultadoIndicadorMeta>();
            this.MItblMatrizIndicadorResultadoIndicadorMeta1 = new HashSet<MItblMatrizIndicadorResultadoIndicadorMeta>();
            this.MItblPlanDesarrollo = new HashSet<MItblPlanDesarrollo>();
            this.MItblPlanDesarrollo1 = new HashSet<MItblPlanDesarrollo>();
            this.MItblPlanDesarrolloEstructura = new HashSet<MItblPlanDesarrolloEstructura>();
            this.MItblPlanDesarrolloEstructura1 = new HashSet<MItblPlanDesarrolloEstructura>();
            this.MItblMatrizIndicadorResultadoIndicador = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicador1 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicadorFormulaVariable = new HashSet<MItblMatrizIndicadorResultadoIndicadorFormulaVariable>();
            this.MItblMatrizIndicadorResultadoIndicadorFormulaVariable1 = new HashSet<MItblMatrizIndicadorResultadoIndicadorFormulaVariable>();
            this.MItblMatrizConfiguracionPresupuestalSeguimientoVariable = new HashSet<MItblMatrizConfiguracionPresupuestalSeguimientoVariable>();
            this.MItblMatrizConfiguracionPresupuestalSeguimientoVariable1 = new HashSet<MItblMatrizConfiguracionPresupuestalSeguimientoVariable>();
            this.MItblControlMaestroFrecuenciaMedicion = new HashSet<MItblControlMaestroFrecuenciaMedicion>();
            this.MItblControlMaestroFrecuenciaMedicion1 = new HashSet<MItblControlMaestroFrecuenciaMedicion>();
            this.MItblControlMaestroFrecuenciaMedicionNivel = new HashSet<MItblControlMaestroFrecuenciaMedicionNivel>();
            this.MItblControlMaestroFrecuenciaMedicionNivel1 = new HashSet<MItblControlMaestroFrecuenciaMedicionNivel>();
            this.ARtblInvitacionCompra = new HashSet<ARtblInvitacionCompra>();
            this.ARtblInvitacionCompra1 = new HashSet<ARtblInvitacionCompra>();
            this.ARtblInvitacionCompraDetalle = new HashSet<ARtblInvitacionCompraDetalle>();
            this.ARtblInvitacionCompraDetalle1 = new HashSet<ARtblInvitacionCompraDetalle>();
            this.ARtblInventarioAjusteDetalle = new HashSet<ARtblInventarioAjusteDetalle>();
            this.ARtblControlMaestroConceptoAjusteInventario = new HashSet<ARtblControlMaestroConceptoAjusteInventario>();
            this.ARtblControlMaestroConceptoAjusteInventario1 = new HashSet<ARtblControlMaestroConceptoAjusteInventario>();
            this.ARtblInventarioMovimiento = new HashSet<ARtblInventarioMovimiento>();
            this.GRtblRol = new HashSet<GRtblRol>();
            this.GRtblRol1 = new HashSet<GRtblRol>();
            this.GRtblRolMenu = new HashSet<GRtblRolMenu>();
            this.GRtblRolMenu1 = new HashSet<GRtblRolMenu>();
            this.ARtblInvitacionArticulo = new HashSet<ARtblInvitacionArticulo>();
            this.ARtblInvitacionArticulo1 = new HashSet<ARtblInvitacionArticulo>();
            this.ARtblInvitacionArticuloDetalle = new HashSet<ARtblInvitacionArticuloDetalle>();
            this.ARtblInvitacionArticuloDetalle1 = new HashSet<ARtblInvitacionArticuloDetalle>();
            this.MItblMatrizConfiguracionPresupuestalDetalle = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
            this.MItblMatrizConfiguracionPresupuestalDetalle1 = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
            this.GRtblPermisoFicha = new HashSet<GRtblPermisoFicha>();
            this.GRtblPermisoFicha1 = new HashSet<GRtblPermisoFicha>();
            this.GRtblUsarioPermiso = new HashSet<GRtblUsarioPermiso>();
            this.GRtblUsarioPermiso1 = new HashSet<GRtblUsarioPermiso>();
            this.GRtblUsarioPermiso2 = new HashSet<GRtblUsarioPermiso>();
            this.ARtblInvitacionCompraProveedor = new HashSet<ARtblInvitacionCompraProveedor>();
            this.ARtblInvitacionCompraProveedor1 = new HashSet<ARtblInvitacionCompraProveedor>();
            this.ArtblInvitacionCompraProveedorCotizacion = new HashSet<ArtblInvitacionCompraProveedorCotizacion>();
            this.ArtblInvitacionCompraProveedorCotizacion1 = new HashSet<ArtblInvitacionCompraProveedorCotizacion>();
            this.ARtblCortesia = new HashSet<ARtblCortesia>();
            this.ARtblCortesia1 = new HashSet<ARtblCortesia>();
            this.ARtblCortesiaDetalle = new HashSet<ARtblCortesiaDetalle>();
            this.ARtblCortesiaDetalle1 = new HashSet<ARtblCortesiaDetalle>();
            this.ARtblTransferencia = new HashSet<ARtblTransferencia>();
            this.ARtblTransferencia1 = new HashSet<ARtblTransferencia>();
            this.ARtblTransferenciaMovto = new HashSet<ARtblTransferenciaMovto>();
            this.ARtblTransferenciaMovto1 = new HashSet<ARtblTransferenciaMovto>();
            this.ARtblInventarioFisico = new HashSet<ARtblInventarioFisico>();
            this.ARtblInventarioFisico1 = new HashSet<ARtblInventarioFisico>();
            this.ARtblInventarioFisico2 = new HashSet<ARtblInventarioFisico>();
            this.GRtblAlertaConfiguracion = new HashSet<GRtblAlertaConfiguracion>();
            this.GRtblAlertaConfiguracion1 = new HashSet<GRtblAlertaConfiguracion>();
            this.GRtblAlerta = new HashSet<GRtblAlerta>();
            this.ARtblInventarioMovimientoAgrupador = new HashSet<ARtblInventarioMovimientoAgrupador>();
        }
    
        public int UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<byte> RolId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public bool Activo { get; set; }
        public bool Borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblAlmacenProducto> ARtblAlmacenProductoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblAlmacenProducto> ARtblAlmacenProductoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionArea> ARtblControlMaestroConfiguracionAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionArea> ARtblControlMaestroConfiguracionAreas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionAreaAlmacen> ARtblControlMaestroConfiguracionAreaAlmacens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionAreaAlmacen> ARtblControlMaestroConfiguracionAreaAlmacens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionAreaProyecto> ARtblControlMaestroConfiguracionAreaProyectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionAreaProyecto> ARtblControlMaestroConfiguracionAreaProyectoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionMontoCompra> ARtblControlMaestroConfiguracionMontoCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionMontoCompra> ARtblControlMaestroConfiguracionMontoCompras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioAjuste> ARtblInventarioAjustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblProveedorProspecto> ARtblProveedorProspectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblProveedorProspecto> ARtblProveedorProspectoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterial> ARtblRequisicionMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterial> ARtblRequisicionMaterials1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterialDetalle> ARtblRequisicionMaterialDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterialDetalle> ARtblRequisicionMaterialDetalles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroControlPeriodo> MItblControlMaestroControlPeriodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroControlPeriodo> MItblControlMaestroControlPeriodo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroDimension> MItblControlMaestroDimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroDimension> MItblControlMaestroDimension1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroDimensionNivel> MItblControlMaestroDimensionNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroDimensionNivel> MItblControlMaestroDimensionNivel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroTipoIndicador> MItblControlMaestroTipoIndicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroTipoIndicador> MItblControlMaestroTipoIndicador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroTipoIndicadorNivel> MItblControlMaestroTipoIndicadorNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroTipoIndicadorNivel> MItblControlMaestroTipoIndicadorNivel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedida> MItblControlMaestroUnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedida> MItblControlMaestroUnidadMedida1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaDimension> MItblControlMaestroUnidadMedidaDimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaDimension> MItblControlMaestroUnidadMedidaDimension1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaFormulaVariable> MItblControlMaestroUnidadMedidaFormulaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaFormulaVariable> MItblControlMaestroUnidadMedidaFormulaVariable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestal> MItblMatrizConfiguracionPresupuestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestal> MItblMatrizConfiguracionPresupuestal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultado> MItblMatrizIndicadorResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultado> MItblMatrizIndicadorResultado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorMeta> MItblMatrizIndicadorResultadoIndicadorMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorMeta> MItblMatrizIndicadorResultadoIndicadorMeta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrollo> MItblPlanDesarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrollo> MItblPlanDesarrollo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrolloEstructura> MItblPlanDesarrolloEstructura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrolloEstructura> MItblPlanDesarrolloEstructura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorFormulaVariable> MItblMatrizIndicadorResultadoIndicadorFormulaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorFormulaVariable> MItblMatrizIndicadorResultadoIndicadorFormulaVariable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalSeguimientoVariable> MItblMatrizConfiguracionPresupuestalSeguimientoVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalSeguimientoVariable> MItblMatrizConfiguracionPresupuestalSeguimientoVariable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroFrecuenciaMedicion> MItblControlMaestroFrecuenciaMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroFrecuenciaMedicion> MItblControlMaestroFrecuenciaMedicion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroFrecuenciaMedicionNivel> MItblControlMaestroFrecuenciaMedicionNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroFrecuenciaMedicionNivel> MItblControlMaestroFrecuenciaMedicionNivel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompra> ARtblInvitacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompra> ARtblInvitacionCompra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraDetalle> ARtblInvitacionCompraDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraDetalle> ARtblInvitacionCompraDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioAjusteDetalle> ARtblInventarioAjusteDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConceptoAjusteInventario> ARtblControlMaestroConceptoAjusteInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConceptoAjusteInventario> ARtblControlMaestroConceptoAjusteInventario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimiento> ARtblInventarioMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRol> GRtblRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRol> GRtblRol1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRolMenu> GRtblRolMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRolMenu> GRtblRolMenu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticulo> ARtblInvitacionArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticulo> ARtblInvitacionArticulo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticuloDetalle> ARtblInvitacionArticuloDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticuloDetalle> ARtblInvitacionArticuloDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblPermisoFicha> GRtblPermisoFicha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblPermisoFicha> GRtblPermisoFicha1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblUsarioPermiso> GRtblUsarioPermiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblUsarioPermiso> GRtblUsarioPermiso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblUsarioPermiso> GRtblUsarioPermiso2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraProveedor> ARtblInvitacionCompraProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraProveedor> ARtblInvitacionCompraProveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtblInvitacionCompraProveedorCotizacion> ArtblInvitacionCompraProveedorCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtblInvitacionCompraProveedorCotizacion> ArtblInvitacionCompraProveedorCotizacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesia> ARtblCortesia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesia> ARtblCortesia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesiaDetalle> ARtblCortesiaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesiaDetalle> ARtblCortesiaDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferencia> ARtblTransferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferencia> ARtblTransferencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferenciaMovto> ARtblTransferenciaMovto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferenciaMovto> ARtblTransferenciaMovto1 { get; set; }
        public virtual RHtblEmpleado RHtblEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisico> ARtblInventarioFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisico> ARtblInventarioFisico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisico> ARtblInventarioFisico2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlerta> GRtblAlerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimientoAgrupador> ARtblInventarioMovimientoAgrupador { get; set; }
    }
}
