//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRtblAlertaConfiguracion
    {
        public int AlertaConfiguracionId { get; set; }
        public int AlertaEtapaAccionId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> FiguraId { get; set; }
        public int TipoNotificacionId { get; set; }
        public bool EnPlataforma { get; set; }
        public bool EnCorreoElectronico { get; set; }
        public bool Sistema { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro1 { get; set; }
        public virtual GRtblControlMaestro GRtblControlMaestro2 { get; set; }
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual GRtblUsuario GRtblUsuario1 { get; set; }
        public virtual RHtblEmpleado RHtblEmpleado { get; set; }
    }
}
