//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRtblControlMaestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRtblControlMaestro()
        {
            this.ARtblControlMaestroConfiguracionMontoCompras = new HashSet<ARtblControlMaestroConfiguracionMontoCompra>();
            this.ARtblControlMaestroConfiguracionMontoCompras1 = new HashSet<ARtblControlMaestroConfiguracionMontoCompra>();
            this.ARtblProveedorProspectoes = new HashSet<ARtblProveedorProspecto>();
            this.ARtblRequisicionMaterials = new HashSet<ARtblRequisicionMaterial>();
            this.ARtblRequisicionMaterialDetalles = new HashSet<ARtblRequisicionMaterialDetalle>();
            this.MItblControlMaestroControlPeriodo = new HashSet<MItblControlMaestroControlPeriodo>();
            this.MItblControlMaestroDimensionNivel = new HashSet<MItblControlMaestroDimensionNivel>();
            this.MItblControlMaestroTipoIndicadorNivel = new HashSet<MItblControlMaestroTipoIndicadorNivel>();
            this.MItblMatrizConfiguracionPresupuestal = new HashSet<MItblMatrizConfiguracionPresupuestal>();
            this.MItblMatrizIndicadorResultado = new HashSet<MItblMatrizIndicadorResultado>();
            this.MItblMatrizIndicadorResultadoIndicadorMeta = new HashSet<MItblMatrizIndicadorResultadoIndicadorMeta>();
            this.MItblPlanDesarrollo = new HashSet<MItblPlanDesarrollo>();
            this.MItblPlanDesarrollo1 = new HashSet<MItblPlanDesarrollo>();
            this.MItblPlanDesarrolloEstructura = new HashSet<MItblPlanDesarrolloEstructura>();
            this.MItblMatrizIndicadorResultadoIndicador = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicador1 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicador2 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicador3 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicador4 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicadorFormulaVariable = new HashSet<MItblMatrizIndicadorResultadoIndicadorFormulaVariable>();
            this.MItblMatrizConfiguracionPresupuestalSeguimientoVariable = new HashSet<MItblMatrizConfiguracionPresupuestalSeguimientoVariable>();
            this.MItblControlMaestroFrecuenciaMedicionNivel = new HashSet<MItblControlMaestroFrecuenciaMedicionNivel>();
            this.ARtblInvitacionCompra = new HashSet<ARtblInvitacionCompra>();
            this.ARtblInvitacionCompraDetalle = new HashSet<ARtblInvitacionCompraDetalle>();
            this.ARtblInventarioAjusteDetalle = new HashSet<ARtblInventarioAjusteDetalle>();
            this.ARtblControlMaestroConceptoAjusteInventario = new HashSet<ARtblControlMaestroConceptoAjusteInventario>();
            this.ARtblControlMaestroConceptoAjusteInventario1 = new HashSet<ARtblControlMaestroConceptoAjusteInventario>();
            this.ARtblInventarioMovimiento = new HashSet<ARtblInventarioMovimiento>();
            this.ARtblInventarioMovimiento1 = new HashSet<ARtblInventarioMovimiento>();
            this.GRtblMenuPrincipal = new HashSet<GRtblMenuPrincipal>();
            this.GRtblRol = new HashSet<GRtblRol>();
            this.GRtblRolMenu = new HashSet<GRtblRolMenu>();
            this.ARtblInvitacionArticulo = new HashSet<ARtblInvitacionArticulo>();
            this.ARtblInvitacionArticuloDetalle = new HashSet<ARtblInvitacionArticuloDetalle>();
            this.MItblMatrizConfiguracionPresupuestalDetalle = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
            this.MItblMatrizConfiguracionPresupuestalDetalle1 = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
            this.GRtblPermisoFicha = new HashSet<GRtblPermisoFicha>();
            this.GRtblUsarioPermiso = new HashSet<GRtblUsarioPermiso>();
            this.ArtblInvitacionCompraDetallePrecioProveedor = new HashSet<ArtblInvitacionCompraDetallePrecioProveedor>();
            this.ARtblInvitacionCompraProveedor = new HashSet<ARtblInvitacionCompraProveedor>();
            this.ArtblInvitacionCompraProveedorCotizacion = new HashSet<ArtblInvitacionCompraProveedorCotizacion>();
            this.ARtblCortesia = new HashSet<ARtblCortesia>();
            this.ARtblCortesiaDetalle = new HashSet<ARtblCortesiaDetalle>();
            this.ARtblTransferencia = new HashSet<ARtblTransferencia>();
            this.ARtblTransferenciaMovto = new HashSet<ARtblTransferenciaMovto>();
            this.ARtblInventarioFisico = new HashSet<ARtblInventarioFisico>();
            this.GRtblAlertaConfiguracion = new HashSet<GRtblAlertaConfiguracion>();
            this.GRtblAlertaConfiguracion1 = new HashSet<GRtblAlertaConfiguracion>();
            this.GRtblAlertaConfiguracion2 = new HashSet<GRtblAlertaConfiguracion>();
            this.GRtblAlerta = new HashSet<GRtblAlerta>();
            this.ARtblInventarioMovimientoAgrupador = new HashSet<ARtblInventarioMovimientoAgrupador>();
        }
    
        public int ControlId { get; set; }
        public string Control { get; set; }
        public string Valor { get; set; }
        public bool Sistema { get; set; }
        public bool Activo { get; set; }
        public bool ControlSencillo { get; set; }
        public Nullable<int> ModuloId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionMontoCompra> ARtblControlMaestroConfiguracionMontoCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConfiguracionMontoCompra> ARtblControlMaestroConfiguracionMontoCompras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblProveedorProspecto> ARtblProveedorProspectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterial> ARtblRequisicionMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterialDetalle> ARtblRequisicionMaterialDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroControlPeriodo> MItblControlMaestroControlPeriodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroDimensionNivel> MItblControlMaestroDimensionNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroTipoIndicadorNivel> MItblControlMaestroTipoIndicadorNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestal> MItblMatrizConfiguracionPresupuestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultado> MItblMatrizIndicadorResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorMeta> MItblMatrizIndicadorResultadoIndicadorMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrollo> MItblPlanDesarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrollo> MItblPlanDesarrollo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblPlanDesarrolloEstructura> MItblPlanDesarrolloEstructura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicadorFormulaVariable> MItblMatrizIndicadorResultadoIndicadorFormulaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalSeguimientoVariable> MItblMatrizConfiguracionPresupuestalSeguimientoVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroFrecuenciaMedicionNivel> MItblControlMaestroFrecuenciaMedicionNivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompra> ARtblInvitacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraDetalle> ARtblInvitacionCompraDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioAjusteDetalle> ARtblInventarioAjusteDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConceptoAjusteInventario> ARtblControlMaestroConceptoAjusteInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblControlMaestroConceptoAjusteInventario> ARtblControlMaestroConceptoAjusteInventario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimiento> ARtblInventarioMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimiento> ARtblInventarioMovimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblMenuPrincipal> GRtblMenuPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRol> GRtblRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblRolMenu> GRtblRolMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticulo> ARtblInvitacionArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticuloDetalle> ARtblInvitacionArticuloDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblPermisoFicha> GRtblPermisoFicha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblUsarioPermiso> GRtblUsarioPermiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtblInvitacionCompraDetallePrecioProveedor> ArtblInvitacionCompraDetallePrecioProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraProveedor> ARtblInvitacionCompraProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtblInvitacionCompraProveedorCotizacion> ArtblInvitacionCompraProveedorCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesia> ARtblCortesia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesiaDetalle> ARtblCortesiaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferencia> ARtblTransferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblTransferenciaMovto> ARtblTransferenciaMovto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisico> ARtblInventarioFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlertaConfiguracion> GRtblAlertaConfiguracion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRtblAlerta> GRtblAlerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioMovimientoAgrupador> ARtblInventarioMovimientoAgrupador { get; set; }
    }
}
