//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRtblArchivoEstructuraCarpeta
    {
        public int EstructuraCarpetaId { get; set; }
        public string NombreCarpeta { get; set; }
        public string DescripcionCorta { get; set; }
        public Nullable<int> EstructuraReferenciaId { get; set; }
        public Nullable<int> OrigenArchivoId { get; set; }
        public Nullable<bool> NombreCalculado { get; set; }
        public Nullable<int> TipoCalculo { get; set; }
        public bool Vigente { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> CreadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
