//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRtblUsarioPermiso
    {
        public int UsuarioPermisoId { get; set; }
        public int UsuarioId { get; set; }
        public int PermisoFichaId { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        private GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblPermisoFicha GRtblPermisoFicha { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        private GRtblUsuario GRtblUsuario2 { get; set; }
    }
}
