//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblControlMaestroUnidadMedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblControlMaestroUnidadMedida()
        {
            this.MItblControlMaestroUnidadMedidaDimension = new HashSet<MItblControlMaestroUnidadMedidaDimension>();
            this.MItblControlMaestroUnidadMedidaFormulaVariable = new HashSet<MItblControlMaestroUnidadMedidaFormulaVariable>();
            this.MItblMatrizIndicadorResultadoIndicador = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
        }
    
        public int UnidadMedidaId { get; set; }
        public string Nombre { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public string Formula { get; set; }
        public bool Sistema { get; set; }
    
        public virtual GRtblUsuario GRtblUsuario { get; set; }
        public virtual GRtblUsuario GRtblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaDimension> MItblControlMaestroUnidadMedidaDimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblControlMaestroUnidadMedidaFormulaVariable> MItblControlMaestroUnidadMedidaFormulaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador { get; set; }
    }
}
