//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblMatrizIndicadorResultado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblMatrizIndicadorResultado()
        {
            this.MItblMatrizConfiguracionPresupuestal = new HashSet<MItblMatrizConfiguracionPresupuestal>();
            this.MItblMatrizIndicadorResultadoIndicador = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
        }
    
        public int MIRId { get; set; }
        public string Codigo { get; set; }
        public string Ejercicio { get; set; }
        public int PlanDesarrolloId { get; set; }
        public string PoblacionObjetivo { get; set; }
        public string ProgramaPresupuestarioId { get; set; }
        public System.DateTime FechaFinConfiguracion { get; set; }
        public int PlanDesarrolloEstructuraId { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        private GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizConfiguracionPresupuestal> MItblMatrizConfiguracionPresupuestal { get; set; }
        private MItblPlanDesarrollo MItblPlanDesarrollo { get; set; }
        private MItblPlanDesarrolloEstructura MItblPlanDesarrolloEstructura { get; set; }
        private tblProgramaGobierno tblProgramaGobierno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador { get; set; }
    }
}
