//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblMatrizConfiguracionPresupuestal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblMatrizConfiguracionPresupuestal()
        {
            this.MItblMatrizConfiguracionPresupuestalDetalle = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
        }
    
        public int ConfiguracionPresupuestoId { get; set; }
        public int MIRId { get; set; }
        public decimal PresupuestoPorEjercer { get; set; }
        public decimal PresupuestoDevengado { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        public virtual MItblMatrizIndicadorResultado MItblMatrizIndicadorResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle { get; set; }
    }
}
