//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblMatrizIndicadorResultadoIndicadorFormulaVariable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblMatrizIndicadorResultadoIndicadorFormulaVariable()
        {
            this.MItblMatrizConfiguracionPresupuestalSeguimientoVariable = new HashSet<MItblMatrizConfiguracionPresupuestalSeguimientoVariable>();
        }
    
        public int MIRIndicadorFormulaVariableId { get; set; }
        public int MIRIndicadorId { get; set; }
        public int UnidadMedidaFormulaVariableId { get; set; }
        public string DescripcionVariable { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        private GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        private MItblControlMaestroUnidadMedidaFormulaVariable MItblControlMaestroUnidadMedidaFormulaVariable { get; set; }
        private MItblMatrizIndicadorResultadoIndicador MItblMatrizIndicadorResultadoIndicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizConfiguracionPresupuestalSeguimientoVariable> MItblMatrizConfiguracionPresupuestalSeguimientoVariable { get; set; }
    }
}
