//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblPlanDesarrolloEstructura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblPlanDesarrolloEstructura()
        {
            this.MItblMatrizIndicadorResultado = new HashSet<MItblMatrizIndicadorResultado>();
            this.MItblPlanDesarrolloEstructura1 = new HashSet<MItblPlanDesarrolloEstructura>();
        }
    
        public int PlanDesarrolloEstructuraId { get; set; }
        public int PlanDesarrolloId { get; set; }
        public Nullable<int> EstructuraPadreId { get; set; }
        public string Nombre { get; set; }
        public string Etiqueta { get; set; }
        public int Orden { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
    
        private GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizIndicadorResultado> MItblMatrizIndicadorResultado { get; set; }
        private MItblPlanDesarrollo MItblPlanDesarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblPlanDesarrolloEstructura> MItblPlanDesarrolloEstructura1 { get; set; }
        private MItblPlanDesarrolloEstructura MItblPlanDesarrolloEstructura2 { get; set; }
    }
}
