//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MItblMatrizIndicadorResultadoIndicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MItblMatrizIndicadorResultadoIndicador()
        {
            this.MItblMatrizIndicadorResultadoIndicador1 = new HashSet<MItblMatrizIndicadorResultadoIndicador>();
            this.MItblMatrizIndicadorResultadoIndicadorFormulaVariable = new HashSet<MItblMatrizIndicadorResultadoIndicadorFormulaVariable>();
            this.MItblMatrizIndicadorResultadoIndicadorMeta = new HashSet<MItblMatrizIndicadorResultadoIndicadorMeta>();
            this.MItblMatrizConfiguracionPresupuestalDetalle = new HashSet<MItblMatrizConfiguracionPresupuestalDetalle>();
        }
    
        public int MIRIndicadorId { get; set; }
        public int MIRId { get; set; }
        public int NivelIndicadorId { get; set; }
        public string NombreIndicador { get; set; }
        public string ResumenNarrativo { get; set; }
        public string DefinicionIndicador { get; set; }
        public int TipoIndicadorId { get; set; }
        public int DimensionId { get; set; }
        public int UnidadMedidaId { get; set; }
        public int FrecuenciaMedicionId { get; set; }
        public int SentidoId { get; set; }
        public Nullable<int> TipoComponenteId { get; set; }
        public Nullable<int> MIRIndicadorComponenteId { get; set; }
        public string ProyectoId { get; set; }
        public Nullable<decimal> PorcentajeProyecto { get; set; }
        public Nullable<decimal> MontoProyecto { get; set; }
        public Nullable<decimal> PorcentajeActividad { get; set; }
        public Nullable<decimal> MontoActividad { get; set; }
        public string AnioBase { get; set; }
        public decimal ValorBase { get; set; }
        public decimal AceptableDesde { get; set; }
        public decimal AceptableHasta { get; set; }
        public decimal ConRiesgoDesde { get; set; }
        public decimal ConRiesgoHasta { get; set; }
        public decimal CriticoPorDebajo { get; set; }
        public decimal CriticoPorEncima { get; set; }
        public int FormulaId { get; set; }
        public string DescripcionFormula { get; set; }
        public string FuenteInformacion { get; set; }
        public string MedioVerificacion { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPorId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> ModificadoPorId { get; set; }
        public byte[] Timestamp { get; set; }
        public string Codigo { get; set; }
        public string DescripcionBase { get; set; }
    
        private GRtblControlMaestro GRtblControlMaestro { get; set; }
        private GRtblControlMaestro GRtblControlMaestro1 { get; set; }
        private GRtblControlMaestro GRtblControlMaestro2 { get; set; }
        private GRtblControlMaestro GRtblControlMaestro3 { get; set; }
        private GRtblControlMaestro GRtblControlMaestro4 { get; set; }
        private GRtblUsuario GRtblUsuario { get; set; }
        private GRtblUsuario GRtblUsuario1 { get; set; }
        private MItblControlMaestroDimension MItblControlMaestroDimension { get; set; }
        private MItblControlMaestroTipoIndicador MItblControlMaestroTipoIndicador { get; set; }
        private MItblControlMaestroUnidadMedida MItblControlMaestroUnidadMedida { get; set; }
        private MItblMatrizIndicadorResultado MItblMatrizIndicadorResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizIndicadorResultadoIndicador> MItblMatrizIndicadorResultadoIndicador1 { get; set; }
        private MItblMatrizIndicadorResultadoIndicador MItblMatrizIndicadorResultadoIndicador2 { get; set; }
        private tblProyecto tblProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizIndicadorResultadoIndicadorFormulaVariable> MItblMatrizIndicadorResultadoIndicadorFormulaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizIndicadorResultadoIndicadorMeta> MItblMatrizIndicadorResultadoIndicadorMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<MItblMatrizConfiguracionPresupuestalDetalle> MItblMatrizConfiguracionPresupuestalDetalle { get; set; }
    }
}
