//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIvwListadoMatrizConfiguracionPresupuestalSeguimientoVariable
    {
        public int MIRId { get; set; }
        public string Codigo { get; set; }
        public string Ejercicio { get; set; }
        public string TipoPlanDesarrollo { get; set; }
        public string NombrePlanPeriodo { get; set; }
        public string ProgramaPresupuestario { get; set; }
        public Nullable<int> Indicadores { get; set; }
    }
}
