//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompraDet
    {
        public int CompraDetId { get; set; }
        public int CompraId { get; set; }
        public string ProductoId { get; set; }
        public string TarifaImpuestoId { get; set; }
        public Nullable<int> RefOrdenCompraDetId { get; set; }
        public int CuentaPresupuestalEgrId { get; set; }
        public string Descripcion { get; set; }
        public double Cantidad { get; set; }
        public decimal Costo { get; set; }
        public decimal Importe { get; set; }
        public double IEPS { get; set; }
        public double Ajuste { get; set; }
        public double IVA { get; set; }
        public double ISH { get; set; }
        public double RetencionISR { get; set; }
        public double RetencionCedular { get; set; }
        public double RetencionIVA { get; set; }
        public double TotalPresupuesto { get; set; }
        public double Total { get; set; }
    
        public virtual tblCompra tblCompra { get; set; }
        public virtual tblCuentaPresupuestalEgr tblCuentaPresupuestalEgr { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblTarifaImpuesto tblTarifaImpuesto { get; set; }
    }
}
