//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompra()
        {
            this.tblCompraDet = new HashSet<tblCompraDet>();
            this.ARtblCompraCancelInfo = new HashSet<ARtblCompraCancelInfo>();
        }
    
        public int CompraId { get; set; }
        public int ProveedorId { get; set; }
        public string AlmacenId { get; set; }
        public string TipoOperacionId { get; set; }
        public int TipoComprobanteFiscalId { get; set; }
        public string FolioFactura { get; set; }
        public int Ejercicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public System.DateTime FechaContrarecibo { get; set; }
        public System.DateTime FechaPagoProgramado { get; set; }
        public string Status { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> PagoProveedorId { get; set; }
    
        public virtual tblAlmacen tblAlmacen { get; set; }
        public virtual tblProveedor tblProveedor { get; set; }
        public virtual tblTipoComprobanteFiscal tblTipoComprobanteFiscal { get; set; }
        public virtual tblTipoOperacion tblTipoOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompraDet> tblCompraDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCompraCancelInfo> ARtblCompraCancelInfo { get; set; }
    }
}
