//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObjetoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblObjetoGasto()
        {
            this.tblProducto = new HashSet<tblProducto>();
            this.tblCuentaPresupuestalEgr = new HashSet<tblCuentaPresupuestalEgr>();
        }
    
        public string ObjetoGastoId { get; set; }
        public string Nombre { get; set; }
        public bool GeneraCuentas { get; set; }
        public bool Editable { get; set; }
        public bool CuentaDeRigistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducto> tblProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCuentaPresupuestalEgr> tblCuentaPresupuestalEgr { get; set; }
    }
}
