//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProveedor()
        {
            this.tblOrdenCompra = new HashSet<tblOrdenCompra>();
            this.ARtblInvitacionCompra = new HashSet<ARtblInvitacionCompra>();
            this.tblCompra = new HashSet<tblCompra>();
            this.ARtblInvitacionArticulo = new HashSet<ARtblInvitacionArticulo>();
            this.ArtblInvitacionCompraDetallePrecioProveedor = new HashSet<ArtblInvitacionCompraDetallePrecioProveedor>();
            this.ARtblInvitacionCompraProveedor = new HashSet<ARtblInvitacionCompraProveedor>();
            this.ARtblCortesia = new HashSet<ARtblCortesia>();
        }
    
        public int ProveedorId { get; set; }
        public string TipoProveedorId { get; set; }
        public string PaisId { get; set; }
        public string EstadoId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public string RazonSocial { get; set; }
        public string Status { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string TipoOperacionId { get; set; }
        public int TipoComprobanteFiscalId { get; set; }
        public string Domicilio { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contacto1 { get; set; }
        public string Contacto2 { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CatalogoCuentaId { get; set; }
        public string Origen { get; set; }
    
        public virtual tblCatalogoCuenta tblCatalogoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdenCompra> tblOrdenCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompra> ARtblInvitacionCompra { get; set; }
        public virtual tblTipoComprobanteFiscal tblTipoComprobanteFiscal { get; set; }
        public virtual tblTipoOperacion tblTipoOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompra> tblCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionArticulo> ARtblInvitacionArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtblInvitacionCompraDetallePrecioProveedor> ArtblInvitacionCompraDetallePrecioProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInvitacionCompraProveedor> ARtblInvitacionCompraProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblCortesia> ARtblCortesia { get; set; }
    }
}
