//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTipoGasto()
        {
            this.ARtblInventarioFisicoDetalle = new HashSet<ARtblInventarioFisicoDetalle>();
            this.ARtblRequisicionMaterialDetalle = new HashSet<ARtblRequisicionMaterialDetalle>();
            this.tblCuentaPresupuestalEgr = new HashSet<tblCuentaPresupuestalEgr>();
            this.ARtblInventarioAjusteDetalle = new HashSet<ARtblInventarioAjusteDetalle>();
        }
    
        public string TipoGastoId { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioFisicoDetalle> ARtblInventarioFisicoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblRequisicionMaterialDetalle> ARtblRequisicionMaterialDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCuentaPresupuestalEgr> tblCuentaPresupuestalEgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARtblInventarioAjusteDetalle> ARtblInventarioAjusteDetalle { get; set; }
    }
}
